stages:
  - build_backend

build_backend:
  stage: build_backend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - backend/**/*
      when: always
  image: amazoncorretto:17-alpine-jdk
  cache:
    paths:
      - backend/.gradle/
      - backend/build/
    key: $CI_PROJECT_NAME-backend-cache
  before_script:
    - apk add --no-cache git
    - cd backend
  script:
    - chmod +x ./gradlew
    - ./gradlew build checkstyleMain checkstyleTest --build-cache -Dspring.profiles.active=dev
    - bash scripts/ci/generate-codequality-report-from-checkstyle.sh build/reports/checkstyle/main.xml > tmp-main.json || echo "[]" > tmp-main.json
    - bash scripts/ci/generate-codequality-report-from-checkstyle.sh build/reports/checkstyle/test.xml > tmp-test.json || echo "[]" > tmp-test.json
    - echo "[" > ../code-quality-report.json
    - tail -n +2 tmp-main.json | head -n -1 >> ../code-quality-report.json
    - if [ -s tmp-test.json ]; then printf ",\n" >> ../code-quality-report.json; fi
    - tail -n +2 tmp-test.json | head -n -1 >> ../code-quality-report.json
    - echo "]" >> ../code-quality-report.json
  artifacts:
    reports:
      codequality: ../code-quality-report.json
    paths:
      - build/
      - ../code-quality-report.json
    expire_in: 1 week
