version: '3.8'

services:

  redis:
    image: redis:7.2
    container_name: yoittang_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: yoittang_jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    restart: unless-stopped

volumes:
  redis_data:
  jenkins_home:
