version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
    networks:
      - yoittang_infra
    restart: unless-stopped

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yoittang_infra
    restart: unless-stopped

  jenkins:
    build:
      context: infra
      dockerfile: jenkins.Dockerfile
    image: yoittang_jenkins:latest
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/S12P31A502/backend/dev.env:/var/jenkins_home/dev.env:ro
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - yoittang_infra
    restart: unless-stopped

volumes:
  redis_data:
  jenkins_home:

networks:
  yoittang_infra:
    external: true
    name: yoittang_infra

