version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: yoittang_backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./backend/dev.env:/app/dev.env
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: yoittang_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
