version: '3.8'

services:
  backend-green:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: yoittang_backend_green
    ports:
      - "18082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - ../backend/dev.env
    restart: unless-stopped

