version: '3.8'

services:
  backend-blue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yoittang_backend_blue
    ports:
      - "18081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - ./backend/dev.env
    restart: unless-stopped

