spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET}
      access-token-expiry: ${JWT_ACCESS_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_EXPIRY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${KAKAO_CLIENT_ID}
            client_secret: ${KAKAO_CLIENT_SECRET}
            client_name : ${KAKAO_CLIENT_NAME}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            redirect-uri-app: ${KAKAO_REDIRECT_URI_APP}
            redirect-uri-web: ${KAKAO_REDIRECT_URI_WEB}
            redirect-uri-app-local: ${KAKAO_REDIRECT_URI_APP_LOCAL}
            redirect-uri-web-local: ${KAKAO_REDIRECT_URI_WEB_LOCAL}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET}