spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

server:
  forward-headers-strategy: NATIVE
  servlet:
    context-path: /api/v1
    encoding:
      enabled: true
      charset: UTF-8
      force: true
